name: Danger
on:
  workflow_call:
jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to target repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Checkout source repository from main branch
        uses: actions/checkout@v4
        with:
          repository: Mone-Inc/CI-CD  # Replace with the source repo name
          ref: main  # Specify the branch as 'main'
          path: source-repo

      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.10 # Look at the `Note for version`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_FILE: source-repo/Dangerfile
